/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csacw;

import bankemployee.Employee;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Pavith Buddhima
 */
public class EmployeeList extends javax.swing.JFrame {
    
      static List<bankemployee.Employee> listOfEmployee= new ArrayList();
    /**
     * Creates new form EmployeeList
     */
    public EmployeeList() {
        initComponents();
 this.setLocationRelativeTo(null);

        listOfEmployee = getAccounts();

        
        DefaultListModel<String> model = new DefaultListModel<>();
        


          System.out.println(listOfEmployee.size());

        for ( int i = 0; i < listOfEmployee.size(); i++ ){
            
          model.addElement("name:    "+listOfEmployee.get(i).getEmpName()+" ------- position:    "+listOfEmployee.get(i).getEmpPosition());
          
          
            System.out.println("hi");
            System.out.println(listOfEmployee.get(i).getEmpName());
          

          
                  
        }
        lstEmp.setModel(model);

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        lblEmpLst = new javax.swing.JLabel();
        lblMess1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlEmpAcc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmp = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuitmCusLst = new javax.swing.JMenuItem();
        mnuitmEmpLst = new javax.swing.JMenuItem();
        mnuitmExit = new javax.swing.JMenuItem();
        mnuMyAcc = new javax.swing.JMenu();
        mnuitmAccLogout = new javax.swing.JMenuItem();
        mnuitmAccLogin = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblEmpLst.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        lblEmpLst.setText("Employee List");

        lblMess1.setText("PRESS \"CREATE\" TO CREATE A NEW EMPLOYEE ACCOUNT");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));

        pnlEmpAcc.setBorder(javax.swing.BorderFactory.createTitledBorder("Select A Employee Account"));

        lstEmp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lstEmp.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmp);

        javax.swing.GroupLayout pnlEmpAccLayout = new javax.swing.GroupLayout(pnlEmpAcc);
        pnlEmpAcc.setLayout(pnlEmpAccLayout);
        pnlEmpAccLayout.setHorizontalGroup(
            pnlEmpAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmpAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEmpAccLayout.setVerticalGroup(
            pnlEmpAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnuFile.setText("File");

        mnuitmCusLst.setText("Customer List");
        mnuitmCusLst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmCusLstActionPerformed(evt);
            }
        });
        mnuFile.add(mnuitmCusLst);

        mnuitmEmpLst.setText("Employee List");
        mnuFile.add(mnuitmEmpLst);

        mnuitmExit.setText("Exit");
        mnuitmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuitmExit);

        jMenuBar1.add(mnuFile);

        mnuMyAcc.setText("MyAccount");

        mnuitmAccLogout.setText("LogOut");
        mnuitmAccLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmAccLogoutActionPerformed(evt);
            }
        });
        mnuMyAcc.add(mnuitmAccLogout);

        mnuitmAccLogin.setText("LogIn");
        mnuMyAcc.add(mnuitmAccLogin);

        jMenuBar1.add(mnuMyAcc);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(pnlEmpAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblEmpLst, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblMess1)
                        .addGap(8, 8, 8)
                        .addComponent(btnCreate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEmpLst, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEmpAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMess1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitmAccLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmAccLogoutActionPerformed
        Login login = new Login();
        this.hide();
        login.show();
    }//GEN-LAST:event_mnuitmAccLogoutActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateEmployee createE = new CreateEmployee();
        createE.show(true);
        this.hide();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void mnuitmCusLstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmCusLstActionPerformed
        CustomerList customerList = new CustomerList();
        this.hide();
        customerList.show();
    }//GEN-LAST:event_mnuitmCusLstActionPerformed

    private void mnuitmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuitmExitActionPerformed

    private void lstEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpMouseClicked
        // TODO add your handling code here:
         int i = lstEmp.getSelectedIndex();
         ManageEmployee manageEmp = new ManageEmployee(listOfEmployee.get(i));
         this.hide();
         manageEmp.show();
        
    }//GEN-LAST:event_lstEmpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmpLst;
    private javax.swing.JLabel lblMess1;
    private javax.swing.JList<String> lstEmp;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMyAcc;
    private javax.swing.JMenuItem mnuitmAccLogin;
    private javax.swing.JMenuItem mnuitmAccLogout;
    private javax.swing.JMenuItem mnuitmCusLst;
    private javax.swing.JMenuItem mnuitmEmpLst;
    private javax.swing.JMenuItem mnuitmExit;
    private javax.swing.JPanel pnlEmpAcc;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<bankemployee.Employee> getAccounts() {
        bankemployee.BankEmployee_Service service = new bankemployee.BankEmployee_Service();
        bankemployee.BankEmployee port = service.getBankEmployeePort();
        return port.getAccounts();
    }





}
