/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csacw;

import javax.swing.JOptionPane;

/**
 *
 * @author Pavith Buddhima
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUPw = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        txtUPw = new javax.swing.JPasswordField();
        lblUName = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        lblBankLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuitmExit = new javax.swing.JMenuItem();
        mnuMyAcc = new javax.swing.JMenu();
        mnuitmAccLogout = new javax.swing.JMenuItem();
        mnuitmAccLogin = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 450));

        lblUPw.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUPw.setText("PASSWORD :");

        txtUName.setToolTipText("");
        txtUName.setPreferredSize(new java.awt.Dimension(140, 32));
        txtUName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNameActionPerformed(evt);
            }
        });

        txtUPw.setToolTipText("Enter your password");
        txtUPw.setPreferredSize(new java.awt.Dimension(140, 32));

        lblUName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUName.setText("USER_NAME :");

        btnLogin.setText("LogIn");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnEmployee.setText("Employee");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        lblBankLogin.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        lblBankLogin.setText("XXXX BANK WEB SERVICE");

        mnuFile.setText("File");

        mnuitmExit.setText("Exit");
        mnuitmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuitmExit);

        jMenuBar1.add(mnuFile);

        mnuMyAcc.setText("MyAccount");

        mnuitmAccLogout.setText("LogOut");
        mnuitmAccLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmAccLogoutActionPerformed(evt);
            }
        });
        mnuMyAcc.add(mnuitmAccLogout);

        mnuitmAccLogin.setText("LogIn");
        mnuMyAcc.add(mnuitmAccLogin);

        jMenuBar1.add(mnuMyAcc);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblUPw, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUName, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(txtUPw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblBankLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUPw, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean isCheck = check(); 
        if(isCheck){
            
        }else{
        
        String uName = txtUName.getText();
        String uPass = String.valueOf(txtUPw.getText());
        String inMessage = login(uName, uPass);
        String message1 = "Login Successfull!";
        String message2 = "Invalid Login! Please try again";
        if(inMessage.equals(message1)){
            JOptionPane.showMessageDialog(null,message1);
            this.hide();
            CustomerList customerList = new CustomerList();
            customerList.show();
        }
        else{
              JOptionPane.showMessageDialog(null,message2);
        }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void mnuitmAccLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmAccLogoutActionPerformed
        Login login = new Login();
        this.hide();
        login.show();
    }//GEN-LAST:event_mnuitmAccLogoutActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        
        
        boolean isCheck = check(); 
        if(isCheck){
            
        }else{
        
        String uName = txtUName.getText();
        String uPass = String.valueOf(txtUPw.getText());
        String inMessage = login(uName, uPass);
        String message1 = "Login Successfull!";
        String message2 = "Invalid Login! Please try again";
        if(inMessage.equals(message1)){
            JOptionPane.showMessageDialog(null,message1);
        EmployeeList employeeList = new EmployeeList();
        this.hide();
        employeeList.show();
        }
        else{
              JOptionPane.showMessageDialog(null,message2);
        }
        }
        
        
        
        
        
        
        
        

    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void mnuitmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_mnuitmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    
    
    public boolean check(){
        boolean isCheck = false;
        
        if(txtUName.getText().equals("")  || String.valueOf(txtUPw.getText()).equals("")){
            
             JOptionPane.showMessageDialog(null,"UserName & PassWord cannot be EMPTY");
             
            isCheck = true ;
            
        }
        
        return isCheck ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnLogin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBankLogin;
    private javax.swing.JLabel lblUName;
    private javax.swing.JLabel lblUPw;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMyAcc;
    private javax.swing.JMenuItem mnuitmAccLogin;
    private javax.swing.JMenuItem mnuitmAccLogout;
    private javax.swing.JMenuItem mnuitmExit;
    private javax.swing.JTextField txtUName;
    private javax.swing.JPasswordField txtUPw;
    // End of variables declaration//GEN-END:variables

    private static String login(java.lang.String uName, java.lang.String pWord) {
        bankemployee.BankEmployee_Service service = new bankemployee.BankEmployee_Service();
        bankemployee.BankEmployee port = service.getBankEmployeePort();
        return port.login(uName, pWord);
    }
}
